INSERT INTO kindergarten (level, title, vocab) VALUES
('KG', 'Adjectives', 'Big'),
('KG', 'Adjectives', 'Fast'),
('KG', 'Adjectives', 'Short'),
('KG', 'Adjectives', 'Small'),
('KG', 'Adjectives', 'Slow'),
('KG', 'Adjectives', 'Strong'),
('KG', 'Adjectives', 'Tall'),
('KG', 'Adjectives', 'Weak'),
('KG', 'Animals', 'Deer'),
('KG', 'Animals', 'Goat'),
('KG', 'Animals', 'Hen'),
('KG', 'Animals', 'Kitten'),
('KG', 'Animals', 'Lizard'),
('KG', 'Animals', 'Owl'),
('KG', 'Animals', 'Puppy'),
('KG', 'Animals', 'Rooster'),
('KG', 'Animals 1', 'Duck'),
('KG', 'Animals 1', 'Elephant'),
('KG', 'Animals 1', 'Fish'),
('KG', 'Animals 1', 'Gorilla'),
('KG', 'Animals 1', 'Lion'),
('KG', 'Animals 1', 'Penguin'),
('KG', 'Animals 1', 'Rabbit'),
('KG', 'Animals 1', 'Turtle'),
('KG', 'Animals 2', 'Fox'),
('KG', 'Animals 2', 'Giraffe'),
('KG', 'Animals 2', 'Monkey'),
('KG', 'Animals 2', 'Mouse'),
('KG', 'Animals 2', 'Pig'),
('KG', 'Animals 2', 'Snake'),
('KG', 'Animals 2', 'Zebra'),
('KG', 'Animals 2', 'Kangaroo'),
('KG', 'Bedroom', 'Bed'),
('KG', 'Bedroom', 'Blanket'),
('KG', 'Bedroom', 'Curtain'),
('KG', 'Bedroom', 'Lamp'),
('KG', 'Bedroom', 'Mirror'),
('KG', 'Bedroom', 'Pillow'),
('KG', 'Bedroom', 'Table'),
('KG', 'Bedroom', 'Toys'),
('KG', 'Body Parts 1', 'Ears'),
('KG', 'Body Parts 1', 'Eyes'),
('KG', 'Body Parts 1', 'Head'),
('KG', 'Body Parts 1', 'Knees'),
('KG', 'Body Parts 1', 'Mouth'),
('KG', 'Body Parts 1', 'Nose'),
('KG', 'Body Parts 1', 'Shoulders'),
('KG', 'Body Parts 1', 'Toes'),
('KG', 'Body Parts 2', 'Arm'),
('KG', 'Body Parts 2', 'Back'),
('KG', 'Body Parts 2', 'Finger'),
('KG', 'Body Parts 2', 'Foot'),
('KG', 'Body Parts 2', 'Hair'),
('KG', 'Body Parts 2', 'Hand'),
('KG', 'Body Parts 2', 'Neck'),
('KG', 'Body Parts 2', 'Teeth'),
('KG', 'Buildings', 'Castle'),
('KG', 'Buildings', 'Farm'),
('KG', 'Buildings', 'House'),
('KG', 'Buildings', 'Hut'),
('KG', 'Buildings', 'Igloo'),
('KG', 'Buildings', 'Skyscraper'),
('KG', 'Buildings', 'Temple'),
('KG', 'Buildings', 'Teepee'),
('KG', 'Christmas', 'Angel'),
('KG', 'Christmas', 'Bell'),
('KG', 'Christmas', 'Candy Cane'),
('KG', 'Christmas', 'Christmas Tree'),
('KG', 'Christmas', 'Presents'),
('KG', 'Christmas', 'Reindeer'),
('KG', 'Christmas', 'Santa'),
('KG', 'Christmas', 'Snowman'),
('KG', 'Classroom Objects', 'Book'),
('KG', 'Classroom Objects', 'Chair'),
('KG', 'Classroom Objects', 'Computer'),
('KG', 'Classroom Objects', 'Crayon'),
('KG', 'Classroom Objects', 'Pencil'),
('KG', 'Classroom Objects', 'Ruler'),
('KG', 'Classroom Objects', 'Scissors'),
('KG', 'Classroom Objects', 'Paper'),
('KG', 'Clothes1', 'Coat'),
('KG', 'Clothes1', 'Hat'),
('KG', 'Clothes1', 'Shoes'),
('KG', 'Clothes1', 'Shorts'),
('KG', 'Clothes1', 'Skirt'),
('KG', 'Clothes1', 'Socks'),
('KG', 'Clothes1', 'T-shirt'),
('KG', 'Clothes1', 'Trousers'),
('KG', 'Clothes2', 'Jeans'),
('KG', 'Clothes2', 'Mittens'),
('KG', 'Clothes2', 'Rainboots'),
('KG', 'Clothes2', 'Raincoat'),
('KG', 'Clothes2', 'Sandals'),
('KG', 'Clothes2', 'Scarf'),
('KG', 'Clothes2', 'Sneakers'),
('KG', 'Clothes2', 'Sweater'),
('KG', 'Colours', 'Black'),
('KG', 'Colours', 'Blue'),
('KG', 'Colours', 'Green'),
('KG', 'Colours', 'Orange'),
('KG', 'Colours', 'Pink'),
('KG', 'Colours', 'Red'),
('KG', 'Colours', 'White'),
('KG', 'Colours', 'Yellow'),
('KG', 'Cook', 'Bake'),
('KG', 'Cook', 'Boil'),
('KG', 'Cook', 'Fry'),
('KG', 'Cook', 'Grill'),
('KG', 'Cook', 'Mix'),
('KG', 'Cook', 'Roast'),
('KG', 'Cook', 'Slice'),
('KG', 'Cook', 'Stir'),
('KG', 'Desserts', 'Cake'),
('KG', 'Desserts', 'Chocolate'),
('KG', 'Desserts', 'Cookies'),
('KG', 'Desserts', 'Crisps'),
('KG', 'Desserts', 'Donut'),
('KG', 'Desserts', 'Ice Cream'),
('KG', 'Desserts', 'Ice Lolly'),
('KG', 'Desserts', 'Popcorn'),
('KG', 'Drinks', 'Coffee'),
('KG', 'Drinks', 'Hot Chocolate'),
('KG', 'Drinks', 'Lemonade'),
('KG', 'Drinks', 'Milk'),
('KG', 'Drinks', 'Orange Juice'),
('KG', 'Drinks', 'Soda'),
('KG', 'Drinks', 'Tea'),
('KG', 'Drinks', 'Water'),
('KG', 'Family', 'Brother'),
('KG', 'Family', 'Father'),
('KG', 'Family', 'Grandfather'),
('KG', 'Family', 'Grandmother'),
('KG', 'Family', 'Mother'),
('KG', 'Family', 'Parents'),
('KG', 'Family', 'Sister'),
('KG', 'Family', 'Family'),
('KG', 'Fantasy', 'Castle'),
('KG', 'Fantasy', 'Dragon'),
('KG', 'Fantasy', 'King'),
('KG', 'Fantasy', 'Queen'),
('KG', 'Feelings', 'Happy'),
('KG', 'Feelings', 'Hungry'),
('KG', 'Feelings', 'Sad'),
('KG', 'Feelings', 'Sick'),
('KG', 'Feelings', 'Thirsty'),
('KG', 'Feelings', 'Tired'),
('KG', 'Food', 'Chicken'),
('KG', 'Food', 'Eggs'),
('KG', 'Food', 'Hamburger'),
('KG', 'Food', 'Pizza'),
('KG', 'Food', 'Rice'),
('KG', 'Food', 'Salad'),
('KG', 'Food', 'Sandwich'),
('KG', 'Food', 'Steak'),
('KG', 'Fruit', 'Apple'),
('KG', 'Fruit', 'Banana'),
('KG', 'Fruit', 'Cherry'),
('KG', 'Fruit', 'Grapes'),
('KG', 'Fruit', 'Lemon'),
('KG', 'Fruit', 'Orange'),
('KG', 'Fruit', 'Pineapple'),
('KG', 'Fruit', 'Strawberry'),
('KG', 'House', 'Bathroom'),
('KG', 'House', 'Bedroom'),
('KG', 'House', 'Garden'),
('KG', 'House', 'House'),
('KG', 'House', 'Kitchen'),
('KG', 'House', 'Living Room'),
('KG', 'House', 'Study'),
('KG', 'House', 'Wardrobe'),
('KG', 'Insects', 'Ant'),
('KG', 'Insects', 'Bee'),
('KG', 'Insects', 'Butterfly'),
('KG', 'Insects', 'Fly'),
('KG', 'Insects', 'Ladybug'),
('KG', 'Insects', 'Mosquito'),
('KG', 'Insects', 'Spider'),
('KG', 'Insects', 'Worm'),
('KG', 'Jobs', 'Cook'),
('KG', 'Jobs', 'Doctor'),
('KG', 'Jobs', 'Fireman'),
('KG', 'Jobs', 'Nurse'),
('KG', 'Jobs', 'Policeman'),
('KG', 'Jobs', 'Postman'),
('KG', 'Jobs', 'Student'),
('KG', 'Jobs', 'Teacher'),
('KG', 'Nature', 'Flower'),
('KG', 'Nature', 'Grass'),
('KG', 'Nature', 'Moon'),
('KG', 'Nature', 'Mountain'),
('KG', 'Nature', 'Rainbow'),
('KG', 'Nature', 'Stars'),
('KG', 'Nature', 'Sun'),
('KG', 'Nature', 'Tree'),
('KG', 'Nature2', 'Bridge'),
('KG', 'Nature2', 'Cave'),
('KG', 'Nature2', 'Hill'),
('KG', 'Nature2', 'Mud'),
('KG', 'Nature2', 'Path'),
('KG', 'Nature2', 'Sand'),
('KG', 'Nature2', 'Volcano'),
('KG', 'Nature2', 'Waterfall'),
('KG', 'Places', 'Airport'),
('KG', 'Places', 'Bus Stop'),
('KG', 'Places', 'Hospital'),
('KG', 'Places', 'Park'),
('KG', 'Places', 'Restaurant'),
('KG', 'Places', 'School'),
('KG', 'Places', 'Supermarket'),
('KG', 'Places', 'Zoo'),
('KG', 'Prepositions', 'Above'),
('KG', 'Prepositions', 'Behind'),
('KG', 'Prepositions', 'Between'),
('KG', 'Prepositions', 'In'),
('KG', 'Prepositions', 'In front of'),
('KG', 'Prepositions', 'Next to'),
('KG', 'Prepositions', 'On'),
('KG', 'Prepositions', 'Under'),
('KG', 'Shapes', 'Circle'),
('KG', 'Shapes', 'Diamond'),
('KG', 'Shapes', 'Heart'),
('KG', 'Shapes', 'Oval'),
('KG', 'Shapes', 'Rectangle'),
('KG', 'Shapes', 'Square'),
('KG', 'Shapes', 'Star'),
('KG', 'Shapes', 'Triangle'),
('KG', 'Sports', 'Badminton'),
('KG', 'Sports', 'Baseball'),
('KG', 'Sports', 'Basketball'),
('KG', 'Sports', 'Golf'),
('KG', 'Sports', 'Hockey'),
('KG', 'Sports', 'Soccer'),
('KG', 'Sports', 'Tennis'),
('KG', 'Sports', 'Volleyball'),
('KG', 'Transport', 'Airplane'),
('KG', 'Transport', 'Bicycle'),
('KG', 'Transport', 'Boat'),
('KG', 'Transport', 'Bus'),
('KG', 'Transport', 'Car'),
('KG', 'Transport', 'Helicopter'),
('KG', 'Transport', 'Motorbike'),
('KG', 'Transport', 'Train'),
('KG', 'Vegetables', 'Beans'),
('KG', 'Vegetables', 'Carrot'),
('KG', 'Vegetables', 'Corn'),
('KG', 'Vegetables', 'Cucumber'),
('KG', 'Vegetables', 'Mushroom'),
('KG', 'Vegetables', 'Onion'),
('KG', 'Vegetables', 'Potato'),
('KG', 'Vegetables', 'Tomato'),
('KG', 'Verbs', 'Drink'),
('KG', 'Verbs', 'Eat'),
('KG', 'Verbs', 'Listen'),
('KG', 'Verbs', 'Read'),
('KG', 'Verbs', 'Run'),
('KG', 'Verbs', 'Sleep'),
('KG', 'Verbs', 'Walk'),
('KG', 'Verbs', 'Write'),
('KG', 'Verbs2', 'Count'),
('KG', 'Verbs2', 'Cry'),
('KG', 'Verbs2', 'Dance'),
('KG', 'Verbs2', 'Laugh'),
('KG', 'Verbs2', 'Play'),
('KG', 'Verbs2', 'Sing'),
('KG', 'Verbs2', 'Swim'),
('KG', 'Verbs2', 'Watch'),
('KG', 'Weather', 'Cloudy'),
('KG', 'Weather', 'Cold'),
('KG', 'Weather', 'Fine'),
('KG', 'Weather', 'Hot'),
('KG', 'Weather', 'Rainy'),
('KG', 'Weather', 'Snowy'),
('KG', 'Weather', 'Sunny'),
('KG', 'Weather', 'Windy');



INSERT INTO vocab (book, unit, word) VALUES
('Look 1', 0, 'one'),
('Look 1', 0, 'two'),
('Look 1', 0, 'three'),
('Look 1', 0, 'four'),
('Look 1', 0, 'five'),
('Look 1', 0, 'six'),
('Look 1', 0, 'seven'),
('Look 1', 0, 'eight'),
('Look 1', 0, 'nine'),
('Look 1', 0, 'ten'),
('Look 1', 0, 'black'),
('Look 1', 0, 'blue'),
('Look 1', 0, 'brown'),
('Look 1', 0, 'green'),
('Look 1', 0, 'orange'),
('Look 1', 0, 'purple'),
('Look 1', 0, 'red'),
('Look 1', 0, 'white'),
('Look 1', 0, 'yellow'),
('Look 1', 1, 'bag'),
('Look 1', 1, 'book'),
('Look 1', 1, 'crayon'),
('Look 1', 1, 'eraser'),
('Look 1', 1, 'pen'),
('Look 1', 1, 'pencil'),
('Look 1', 1, 'pencil case'),
('Look 1', 1, 'ruler'),
('Look 1', 1, 'poster'),
('Look 1', 1, 'board'),
('Look 1', 1, 'chair'),
('Look 1', 1, 'desk'),
('Look 1', 1, 'apple'),
('Look 1', 1, 'carrot'),
('Look 1', 2, 'ball'),
('Look 1', 2, 'bat'),
('Look 1', 2, 'doll'),
('Look 1', 2, 'game'),
('Look 1', 2, 'kite'),
('Look 1', 2, 'plane'),
('Look 1', 2, 'teddy bear'),
('Look 1', 2, 'train'),
('Look 1', 2, 'marble'),
('Look 1', 2, 'favorite'),
('Look 1', 2, 'fun'),
('Look 1', 2, 'elephant'),
('Look 1', 2, 'fish'),
('Look 1', 2, 'goat'),
('Look 1', 2, 'horse'),
('Look 1', 3, 'boy'),
('Look 1', 3, 'girl'),
('Look 1', 3, 'man'),
('Look 1', 3, 'woman'),
('Look 1', 3, 'museum'),
('Look 1', 3, 'dinosaur'),
('Look 1', 3, 'trip'),
('Look 1', 3, 'insect'),
('Look 1', 3, 'jellyfish'),
('Look 1', 3, 'kiwi'),
('Look 1', 3, 'lamp'),
('Look 1', 4, 'grandpa'),
('Look 1', 4, 'grandma'),
('Look 1', 4, 'dad'),
('Look 1', 4, 'mom'),
('Look 1', 4, 'uncle'),
('Look 1', 4, 'aunt'),
('Look 1', 4, 'baby'),
('Look 1', 4, 'me'),
('Look 1', 4, 'cousin'),
('Look 1', 4, 'middle'),
('Look 1', 4, 'birthday party'),
('Look 1', 4, 'birthday cake'),
('Look 1', 4, 'nose'),
('Look 1', 4, 'orange'),
('Look 1', 4, 'pencil'),
('Look 1', 5, 'leg'),
('Look 1', 5, 'foot'),
('Look 1', 5, 'mouth'),
('Look 1', 5, 'eye'),
('Look 1', 5, 'head'),
('Look 1', 5, 'ear'),
('Look 1', 5, 'arm'),
('Look 1', 5, 'hand'),
('Look 1', 5, 'skeleton'),
('Look 1', 5, 'hair'),
('Look 1', 5, 'body'),
('Look 1', 5, 'face'),
('Look 1', 5, 'queen'),
('Look 1', 5, 'rabbit'),
('Look 1', 5, 'sofa'),
('Look 1', 5, 'table'),
('Look 1', 5, 'umbrella'),
('Look 1', 6, 'bathroom'),
('Look 1', 6, 'bedroom'),
('Look 1', 6, 'kitchen'),
('Look 1', 6, 'living room'),
('Look 1', 6, 'bed'),
('Look 1', 6, 'cabinet'),
('Look 1', 6, 'shower'),
('Look 1', 6, 'TV'),
('Look 1', 6, 'house'),
('Look 1', 6, 'clock'),
('Look 1', 6, 'water'),
('Look 1', 6, 'violin'),
('Look 1', 6, 'wall'),
('Look 1', 6, 'box'),
('Look 1', 6, 'yogurt'),
('Look 1', 6, 'zebra'),
('Look 1', 7, 'library'),
('Look 1', 7, 'park'),
('Look 1', 7, 'playground'),
('Look 1', 7, 'store'),
('Look 1', 7, 'street'),
('Look 1', 7, 'swimming pool'),
('Look 1', 7, 'town center'),
('Look 1', 7, 'zoo'),
('Look 1', 7, 'real'),
('Look 1', 7, 'model'),
('Look 1', 7, 'tiny'),
('Look 1', 7, 'flower'),
('Look 1', 7, 'bag'),
('Look 1', 7, 'bat'),
('Look 1', 7, 'jam'),
('Look 1', 7, 'man'),
('Look 1', 7, 'map'),
('Look 1', 8, 'bee'),
('Look 1', 8, 'bird'),
('Look 1', 8, 'chicken'),
('Look 1', 8, 'cow'),
('Look 1', 8, 'dog'),
('Look 1', 8, 'donkey'),
('Look 1', 8, 'duck'),
('Look 1', 8, 'sheep'),
('Look 1', 8, 'pen'),
('Look 1', 8, 'farmer'),
('Look 1', 8, 'food'),
('Look 1', 8, 'eleven'),
('Look 1', 8, 'twelve'),
('Look 1', 8, 'thirteen'),
('Look 1', 8, 'fourteen'),
('Look 1', 8, 'fifteen'),
('Look 1', 8, 'sixteen'),
('Look 1', 8, 'seventeen'),
('Look 1', 8, 'eighteen'),
('Look 1', 8, 'nineteen'),
('Look 1', 8, 'twenty'),
('Look 1', 8, 'bed'),
('Look 1', 8, 'leg'),
('Look 1', 8, 'pen'),
('Look 1', 8, 'pet'),
('Look 1', 8, 'yes'),
('Look 1', 9, 'dress'),
('Look 1', 9, 'jeans'),
('Look 1', 9, 'pants'),
('Look 1', 9, 'shirt'),
('Look 1', 9, 'shoes'),
('Look 1', 9, 'skirt'),
('Look 1', 9, 'socks'),
('Look 1', 9, 'T-shirt'),
('Look 1', 9, 'scarecrow'),
('Look 1', 9, 'happy'),
('Look 1', 9, 'boots'),
('Look 1', 9, 'hat'),
('Look 1', 9, 'gloves'),
('Look 1', 9, 'big'),
('Look 1', 9, 'bin'),
('Look 1', 9, 'lip'),
('Look 1', 9, 'sit'),
('Look 1', 9, 'six'),
('Look 1', 10, 'banana'),
('Look 1', 10, 'bread'),
('Look 1', 10, 'candy'),
('Look 1', 10, 'lemon'),
('Look 1', 10, 'milk'),
('Look 1', 10, 'potato'),
('Look 1', 10, 'rice'),
('Look 1', 10, 'tomato'),
('Look 1', 10, 'water'),
('Look 1', 10, 'lunch'),
('Look 1', 10, 'tray'),
('Look 1', 10, 'terrible'),
('Look 1', 10, 'great'),
('Look 1', 10, 'dog'),
('Look 1', 10, 'dot'),
('Look 1', 10, 'fox'),
('Look 1', 10, 'mop'),
('Look 1', 10, 'nod'),
('Look 1', 11, 'beach'),
('Look 1', 11, 'beach ball'),
('Look 1', 11, 'boat'),
('Look 1', 11, 'ice cream'),
('Look 1', 11, 'ocean'),
('Look 1', 11, 'sand'),
('Look 1', 11, 'sandcastle'),
('Look 1', 11, 'shell'),
('Look 1', 11, 'sun hat'),
('Look 1', 11, 'mask'),
('Look 1', 11, 'breathe'),
('Look 1', 11, 'snorkel'),
('Look 1', 11, 'flippers'),
('Look 1', 11, 'bug'),
('Look 1', 11, 'bus'),
('Look 1', 11, 'cup'),
('Look 1', 11, 'jug'),
('Look 1', 11, 'run'),
('Look 1', 12, 'fly a kite'),
('Look 1', 12, 'make a cake'),
('Look 1', 12, 'paint a picture'),
('Look 1', 12, 'play a game'),
('Look 1', 12, 'play soccer'),
('Look 1', 12, 'read a book'),
('Look 1', 12, 'sing a song'),
('Look 1', 12, 'write a story'),
('Look 1', 12, 'hot'),
('Look 1', 12, 'paper'),
('Look 1', 12, 'swing'),
('Look 1', 12, 'hat'),
('Look 1', 12, 'red'),
('Look 1', 12, 'kid'),
('Look 1', 12, 'sun'),
('Look 2', 1, 'art'),
('Look 2', 1, 'computers'),
('Look 2', 1, 'English'),
('Look 2', 1, 'gym'),
('Look 2', 1, 'math'),
('Look 2', 1, 'music'),
('Look 2', 1, 'reading'),
('Look 2', 1, 'science'),
('Look 2', 1, 'class'),
('Look 2', 1, 'homework'),
('Look 2', 1, 'grade'),
('Look 2', 1, 'garden'),
('Look 2', 1, 'Thursday'),
('Look 2', 1, 'bath'),
('Look 2', 1, 'birthday'),
('Look 2', 2, 'bike'),
('Look 2', 2, 'building bricks'),
('Look 2', 2, 'camera'),
('Look 2', 2, 'guitar'),
('Look 2', 2, 'markers'),
('Look 2', 2, 'robot'),
('Look 2', 2, 'skateboard'),
('Look 2', 2, 'tablet'),
('Look 2', 2, 'cool'),
('Look 2', 2, 'old'),
('Look 2', 2, 'new'),
('Look 2', 2, 'borrow'),
('Look 2', 2, 'this'),
('Look 2', 2, 'these'),
('Look 2', 2, 'brother'),
('Look 2', 3, 'armchair'),
('Look 2', 3, 'balcony'),
('Look 2', 3, 'bookcase'),
('Look 2', 3, 'dining room'),
('Look 2', 3, 'door'),
('Look 2', 3, 'floor'),
('Look 2', 3, 'mirror'),
('Look 2', 3, 'rug'),
('Look 2', 3, 'window'),
('Look 2', 3, 'inside'),
('Look 2', 3, 'stairs'),
('Look 2', 3, 'wall'),
('Look 2', 3, 'outside'),
('Look 2', 3, 'chair'),
('Look 2', 3, 'lunch'),
('Look 2', 3, 'ship'),
('Look 2', 3, 'fish'),
('Look 2', 4, 'baseball'),
('Look 2', 4, 'basketball'),
('Look 2', 4, 'hockey'),
('Look 2', 4, 'tennis'),
('Look 2', 4, 'bounce'),
('Look 2', 4, 'catch'),
('Look 2', 4, 'hit'),
('Look 2', 4, 'jump'),
('Look 2', 4, 'kick'),
('Look 2', 4, 'throw'),
('Look 2', 4, 'team'),
('Look 2', 4, 'different'),
('Look 2', 4, 'easy'),
('Look 2', 4, 'fantastic'),
('Look 2', 4, 'duck'),
('Look 2', 4, 'socks'),
('Look 2', 4, 'sink'),
('Look 2', 4, 'pink'),
('Look 2', 5, 'builder'),
('Look 2', 5, 'doctor'),
('Look 2', 5, 'farmer'),
('Look 2', 5, 'soccer player'),
('Look 2', 5, 'taxi driver'),
('Look 2', 5, 'young'),
('Look 2', 5, 'work'),
('Look 2', 5, 'job'),
('Look 2', 5, 'use'),
('Look 2', 5, 'skirt'),
('Look 2', 5, 'slide'),
('Look 2', 5, 'small'),
('Look 2', 5, 'snack'),
('Look 2', 5, 'spoon'),
('Look 2', 5, 'stop'),
('Look 2', 5, 'swim'),
('Look 2', 6, 'get up'),
('Look 2', 6, 'get dressed'),
('Look 2', 6, 'eat breakfast'),
('Look 2', 6, 'eat lunch'),
('Look 2', 6, 'eat dinner'),
('Look 2', 6, 'do homework'),
('Look 2', 6, 'take a bath'),
('Look 2', 6, 'go to bed'),
('Look 2', 6, 'hurt'),
('Look 2', 6, 'find'),
('Look 2', 6, 'wait'),
('Look 2', 6, 'love'),
('Look 2', 6, 'black'),
('Look 2', 6, 'clock'),
('Look 2', 6, 'flag'),
('Look 2', 6, 'glass'),
('Look 2', 6, 'plum'),
('Look 2', 7, 'beans'),
('Look 2', 7, 'cheese'),
('Look 2', 7, 'chicken'),
('Look 2', 7, 'egg'),
('Look 2', 7, 'fries'),
('Look 2', 7, 'grapes'),
('Look 2', 7, 'juice'),
('Look 2', 7, 'mango'),
('Look 2', 7, 'pear'),
('Look 2', 7, 'sausage'),
('Look 2', 7, 'put'),
('Look 2', 7, 'money'),
('Look 2', 7, 'get'),
('Look 2', 7, 'burger'),
('Look 2', 7, 'bread'),
('Look 2', 7, 'crab'),
('Look 2', 7, 'dress'),
('Look 2', 7, 'frog'),
('Look 2', 7, 'present'),
('Look 2', 7, 'tree'),
('Look 2', 8, 'dance'),
('Look 2', 8, 'drink'),
('Look 2', 8, 'eat'),
('Look 2', 8, 'hold'),
('Look 2', 8, 'listen to music'),
('Look 2', 8, 'take photos'),
('Look 2', 8, 'balloon'),
('Look 2', 8, 'lemonade'),
('Look 2', 8, 'festival'),
('Look 2', 8, 'enjoy'),
('Look 2', 8, 'bucket'),
('Look 2', 8, 'sing'),
('Look 2', 8, 'long'),
('Look 2', 8, 'angry'),
('Look 2', 9, 'crocodile'),
('Look 2', 9, 'elephant'),
('Look 2', 9, 'giraffe'),
('Look 2', 9, 'hippo'),
('Look 2', 9, 'lion'),
('Look 2', 9, 'monkey'),
('Look 2', 9, 'snake'),
('Look 2', 9, 'tiger'),
('Look 2', 9, 'zebra'),
('Look 2', 9, 'rhino'),
('Look 2', 9, 'fast'),
('Look 2', 9, 'slow'),
('Look 2', 9, 'sleep'),
('Look 2', 9, 'cake'),
('Look 2', 9, 'game'),
('Look 2', 9, 'snake'),
('Look 2', 10, 'cloudy'),
('Look 2', 10, 'cold'),
('Look 2', 10, 'hot'),
('Look 2', 10, 'raining'),
('Look 2', 10, 'snowing'),
('Look 2', 10, 'sunny'),
('Look 2', 10, 'windy'),
('Look 2', 10, 'bring an umbrella'),
('Look 2', 10, 'put on a scarf'),
('Look 2', 10, 'wear a coat'),
('Look 2', 10, 'sky'),
('Look 2', 10, 'rainbow'),
('Look 2', 10, 'bright'),
('Look 2', 10, 'forget'),
('Look 2', 10, 'bike'),
('Look 2', 10, 'kite'),
('Look 2', 10, 'time'),
('Look 2', 11, 'bus'),
('Look 2', 11, 'car'),
('Look 2', 11, 'helicopter'),
('Look 2', 11, 'motorcycle'),
('Look 2', 11, 'plane'),
('Look 2', 11, 'ship'),
('Look 2', 11, 'truck'),
('Look 2', 11, 'come home'),
('Look 2', 11, 'get to school'),
('Look 2', 11, 'ride a bike'),
('Look 2', 11, 'healthy'),
('Look 2', 11, 'snack'),
('Look 2', 11, 'month'),
('Look 2', 11, 'ready'),
('Look 2', 11, 'home'),
('Look 2', 11, 'nose'),
('Look 2', 11, 'cone'),
('Look 2', 12, 'clean'),
('Look 2', 12, 'dirty'),
('Look 2', 12, 'kind'),
('Look 2', 12, 'little'),
('Look 2', 12, 'loud'),
('Look 2', 12, 'naughty'),
('Look 2', 12, 'quiet'),
('Look 2', 12, 'scary'),
('Look 2', 12, 'silly'),
('Look 2', 12, 'smart'),
('Look 2', 12, 'funny'),
('Look 2', 12, 'cartoon'),
('Look 2', 12, 'grown-up'),
('Look 2', 12, 'famous'),
('Look 2', 12, 'cube'),
('Look 2', 12, 'cute'),
('Look 2', 12, 'tube'),
('Look 3', 1, 'the US'),
('Look 3', 1, 'Brazil'),
('Look 3', 1, 'Argentina'),
('Look 3', 1, 'the UK'),
('Look 3', 1, 'Spain'),
('Look 3', 1, 'Poland'),
('Look 3', 1, 'Italy'),
('Look 3', 1, 'Japan'),
('Look 3', 1, 'South Africa'),
('Look 3', 1, 'Australia'),
('Look 3', 1, 'son'),
('Look 3', 1, 'daughter'),
('Look 3', 1, 'parent'),
('Look 3', 1, 'grandparent'),
('Look 3', 1, 'plane'),
('Look 3', 1, 'game'),
('Look 3', 1, 'train'),
('Look 3', 1, 'paint'),
('Look 3', 1, 'play'),
('Look 3', 1, 'Friday'),
('Look 3', 2, 'farm'),
('Look 3', 2, 'field'),
('Look 3', 2, 'forest'),
('Look 3', 2, 'lake'),
('Look 3', 2, 'mountain'),
('Look 3', 2, 'path'),
('Look 3', 2, 'river'),
('Look 3', 2, 'town'),
('Look 3', 2, 'village'),
('Look 3', 2, 'waterfall'),
('Look 3', 2, 'cable car'),
('Look 3', 2, 'subway'),
('Look 3', 2, 'exercise'),
('Look 3', 2, 'tree'),
('Look 3', 2, 'beach'),
('Look 3', 2, 'country'),
('Look 3', 2, 'week'),
('Look 3', 2, 'please'),
('Look 3', 2, 'story'),
('Look 3', 3, 'clean up my'),
('Look 3', 3, 'bedroom'),
('Look 3', 3, 'cook'),
('Look 3', 3, 'feed the dog'),
('Look 3', 3, 'fix my bike'),
('Look 3', 3, 'go shopping'),
('Look 3', 3, 'make my bed'),
('Look 3', 3, 'practice the piano'),
('Look 3', 3, 'take out the'),
('Look 3', 3, 'garbage'),
('Look 3', 3, 'wash the dishes'),
('Look 3', 3, 'water the plants'),
('Look 3', 3, 'pick (fruit)'),
('Look 3', 3, 'recycling'),
('Look 3', 3, 'put away'),
('Look 3', 3, 'night'),
('Look 3', 3, 'right'),
('Look 3', 3, 'my kite'),
('Look 3', 3, 'fly'),
('Look 3', 3, 'ride'),
('Look 3', 4, 'bake'),
('Look 3', 4, 'collect stickers'),
('Look 3', 4, 'do puzzles'),
('Look 3', 4, 'dress up'),
('Look 3', 4, 'make things'),
('Look 3', 4, 'play video games'),
('Look 3', 4, 'play hide-and-seek'),
('Look 3', 4, 'read comic books'),
('Look 3', 4, 'roller-skate'),
('Look 3', 4, 'watch movies'),
('Look 3', 4, 'stick'),
('Look 3', 4, 'teenagers'),
('Look 3', 4, 'interested in'),
('Look 3', 4, 'real'),
('Look 3', 4, 'window'),
('Look 3', 4, 'know'),
('Look 3', 4, 'coat'),
('Look 3', 4, 'home'),
('Look 3', 4, 'closed'),
('Look 3', 5, 'ketchup'),
('Look 3', 5, 'milkshakes'),
('Look 3', 5, 'noodles'),
('Look 3', 5, 'pancakes'),
('Look 3', 5, 'pasta'),
('Look 3', 5, 'salad'),
('Look 3', 5, 'sandwiches'),
('Look 3', 5, 'soup'),
('Look 3', 5, 'vegetables'),
('Look 3', 5, 'cup'),
('Look 3', 5, 'plate'),
('Look 3', 5, 'bowl'),
('Look 3', 5, 'straw'),
('Look 3', 5, 'bottle'),
('Look 3', 5, 'glass'),
('Look 3', 5, 'choose'),
('Look 3', 5, 'blue'),
('Look 3', 5, 'Tuesday'),
('Look 3', 5, 'ruler'),
('Look 3', 5, 'huge'),
('Look 3', 6, 'ant'),
('Look 3', 6, 'bat'),
('Look 3', 6, 'dolphin'),
('Look 3', 6, 'kangaroo'),
('Look 3', 6, 'panda'),
('Look 3', 6, 'parrot'),
('Look 3', 6, 'penguin'),
('Look 3', 6, 'shark'),
('Look 3', 6, 'whale'),
('Look 3', 6, 'waking up'),
('Look 3', 6, 'busy'),
('Look 3', 6, 'lizard'),
('Look 3', 6, 'hungry'),
('Look 3', 6, 'safe'),
('Look 3', 6, 'elephant'),
('Look 3', 6, 'photo'),
('Look 3', 6, 'fish'),
('Look 3', 6, 'fruit'),
('Look 3', 6, 'breakfast'),
('Look 3', 7, 'a beard'),
('Look 3', 7, 'a moustache'),
('Look 3', 7, 'dark hair'),
('Look 3', 7, 'light hair'),
('Look 3', 7, 'curly hair'),
('Look 3', 7, 'straight hair'),
('Look 3', 7, 'fat'),
('Look 3', 7, 'thin'),
('Look 3', 7, 'tall'),
('Look 3', 7, 'round face'),
('Look 3', 7, 'meter'),
('Look 3', 7, 'take (two hours)'),
('Look 3', 7, 'die'),
('Look 3', 7, 'almost'),
('Look 3', 7, 'birthday'),
('Look 3', 7, 'dirty'),
('Look 3', 7, 'short'),
('Look 3', 7, 'morning'),
('Look 3', 7, 'dark'),
('Look 3', 7, 'car'),
('Look 3', 8, 'back'),
('Look 3', 8, 'shoulder'),
('Look 3', 8, 'stomach'),
('Look 3', 8, 'tooth (teeth)'),
('Look 3', 8, 'a cold'),
('Look 3', 8, 'a cough'),
('Look 3', 8, 'a sore neck'),
('Look 3', 8, 'sick'),
('Look 3', 8, 'toothache'),
('Look 3', 8, 'medicine'),
('Look 3', 8, 'calm'),
('Look 3', 8, 'worry'),
('Look 3', 8, 'grade'),
('Look 3', 8, 'now'),
('Look 3', 8, 'down'),
('Look 3', 8, 'bounce'),
('Look 3', 8, 'playground'),
('Look 3', 9, 'building'),
('Look 3', 9, 'bus stop'),
('Look 3', 9, 'café'),
('Look 3', 9, 'hospital'),
('Look 3', 9, 'market'),
('Look 3', 9, 'movie theater'),
('Look 3', 9, 'parking lot'),
('Look 3', 9, 'sports center'),
('Look 3', 9, 'supermarket'),
('Look 3', 9, 'skyscraper'),
('Look 3', 9, 'factory'),
('Look 3', 9, 'shopping center'),
('Look 3', 9, 'birthday'),
('Look 3', 9, 'burger'),
('Look 3', 9, 'world'),
('Look 3', 9, 'person'),
('Look 3', 10, 'bike to school'),
('Look 3', 10, 'climb trees'),
('Look 3', 10, 'cry'),
('Look 3', 10, 'laugh'),
('Look 3', 10, 'need water'),
('Look 3', 10, 'sail'),
('Look 3', 10, 'stay home'),
('Look 3', 10, 'wait for the bus'),
('Look 3', 10, 'walk to school'),
('Look 3', 10, 'archaeologist'),
('Look 3', 10, 'machine'),
('Look 3', 10, 'remains'),
('Look 3', 10, 'change'),
('Look 3', 10, 'air'),
('Look 3', 10, 'hair'),
('Look 3', 10, 'square'),
('Look 3', 10, 'parent'),
('Look 3', 10, 'bear'),
('Look 3', 10, 'wear'),
('Look 3', 11, 'eat outside'),
('Look 3', 11, 'get lost'),
('Look 3', 11, 'go canoeing'),
('Look 3', 11, 'go on a roller coaster'),
('Look 3', 11, 'have a picnic'),
('Look 3', 11, 'make friends'),
('Look 3', 11, 'ride on a motorcycle'),
('Look 3', 11, 'see a shooting star'),
('Look 3', 11, 'sleep in a tent'),
('Look 3', 11, 'swim in a lake'),
('Look 3', 11, 'ski'),
('Look 3', 11, 'sled'),
('Look 3', 11, 'explorer'),
('Look 3', 11, 'face'),
('Look 3', 11, 'pencil'),
('Look 3', 11, 'huge'),
('Look 3', 11, 'giraffe'),
('Look 3', 12, 'art gallery'),
('Look 3', 12, 'dinosaur'),
('Look 3', 12, 'fair'),
('Look 3', 12, 'museum'),
('Look 3', 12, 'ride'),
('Look 3', 12, 'sculpture'),
('Look 3', 12, 'summer camp'),
('Look 3', 12, 'theme park'),
('Look 3', 12, 'water park'),
('Look 3', 12, 'wildlife park'),
('Look 3', 12, 'chef'),
('Look 3', 12, 'star'),
('Look 3', 12, 'circus'),
('Look 3', 12, 'juggle'),
('Look 3', 12, 'skill'),
('Look 3', 12, 'unicycle'),
('Look 3', 12, 'summer'),
('Look 3', 12, 'kangaroo'),
('Look 3', 12, 'holiday'),
('Look 3', 12, 'banana'),
('Look 3', 12, 'waterfall'),
('Look 3', 12, 'travel');


